package com.crudExample.rest.model;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Data   //Resolve issues with getters and setters
@Entity //Tells to the JPA that this object is a entity

public class Product {

    @Id //Indicates to the JPA that this varable is will be the PK
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Indicates that the id will be generated by the database
    private long id;

    private String name;
    private String description;
    private float price;

    public Product() {
    }

    public Product(String name, String description, float price) {
        this.name = name;
        this.description = description;
        this.price = price;
    }

    public long getID() {
        return this.id;
    }
}




